name: Honkit test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
        steps:
        - name: Install honkit
          run: |
              sudo apt -y install libgif-dev calibre npm nodejs
              sudo npm config set strict-ssl false
              sudo npm cache clean -f
              npm install honkit
        - name: Install plugin-github
          run: |
              npm install gitbook-plugin-github
        - name: Install plugin-atoc
          run: |
              npm install gitbook-plugin-atoc
        - name: Install plugin-anchors
          run: |
              npm install gitbook-plugin-anchors
        - name: Install plugin-image-class
          run: |
              npm install gitbook-plugin-image-class
        - name: Install plugin-codesnippet
          run: |
              npm install gitbook-plugin-codesnippet
        - name: Install plugin-last-modified
          run: |
              npm install gitbook-plugin-last-modified
        - name: Install plugin-sitemap
          run: |
              npm install gitbook-plugin-sitemap
        - name: Install plugin-advanced-emoji
          run: |
              npm install gitbook-plugin-advanced-emoji
        - name: Run honkit build
          run: |
              cd ..
              npx honkit build --log debug
