name: Honkit test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
        steps:
        - name: Install honkit
          run: |
              sudo apt-get -y install libgif-dev calibre npm nodejs
			  sudo npm config set strict-ssl false
			  sudo npm cache clean -f
			  sudo npm install -g n
			  sudo n stable
			  sudo npm update -g
			  npm install honkit --save-dev
			  npm install gitbook-plugin-github
			  npm install gitbook-plugin-atoc
			  npm install gitbook-plugin-anchors
			  npm install gitbook-plugin-image-class
			  npm install gitbook-plugin-codesnippet
			  npm install gitbook-plugin-last-modified
			  npm install gitbook-plugin-sitemap
			  npm install gitbook-plugin-advanced-emoji
			  npm install gitbook-plugin-image-class
              npx honkit build
