name: Honkit test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
        steps:
        - name: Install honkit
          run: |
              sudo apt install nodejs npm
              npm init --yes
              npm install honkit --save-dev
              npx honkit build
